In [ ]:
# element accessing row/column
# loc and iloc ......>location and index location based

In [1]:
import pandas as pd
df=pd.DataFrame({"name":['saru','siri','jerisha','suni'],
                 "rollnumbers":['509','497','545','537'],
                 "branch":['cse','ece','civil','eee']},index=[1,2,3,4])

In [2]:
df

name rollnumbers branch
0     saru         509    cse
1     siri         497    ece
2  jerisha         545  civil
3     suni         537    eee

In [3]:
df.set_index(["rollnumbers"])

name branch
rollnumbers                
509             saru    cse
497             siri    ece
545          jerisha  civil
537             suni    eee

In [4]:
df.set_index(["rollnumbers","branch"])

name
rollnumbers branch         
509         cse        saru
497         ece        siri
545         civil   jerisha
537         eee        suni

In [10]:
frame=pd.Series([9,3,5,6,2,"name"])
frame

0       9
1       3
2       5
3       6
4       2
5    name
dtype: object

In [12]:
frame.describe()

count        6
unique       6
top       name
freq         1
dtype: object

In [13]:
frame.count()

6

In [26]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['s','b','c'])
data

s   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [40]:
y=np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
y.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
data=pd.DataFrame(np.arange(20).reshape(5,4),columns=['a','b','c','d'])
data

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [51]:
data.loc[1,'b']=np.nan
data

a     b   c   d
0   0   1.0   2   3
1   4   NaN   6   7
2   8   9.0  10  11
3  12  13.0  14  15
4  16  17.0  18  19

In [54]:
data.isnull().sum()

a    0
b    1
c    0
d    0
dtype: int64

In [47]:
df

name rollnumbers branch
0     saru         509    cse
1     siri         497    ece
2  jerisha         545  civil
3     suni         537    eee

In [56]:
df=data+data
df

a     b   c   d
0   0   2.0   4   6
1   8   NaN  12  14
2  16  18.0  20  22
3  24  26.0  28  30
4  32  34.0  36  38

In [49]:
dd=df.add(data)
dd

a   b branch   c   d name rollnumbers
0 NaN NaN    NaN NaN NaN  NaN         NaN
1 NaN NaN    NaN NaN NaN  NaN         NaN
2 NaN NaN    NaN NaN NaN  NaN         NaN
3 NaN NaN    NaN NaN NaN  NaN         NaN
4 NaN NaN    NaN NaN NaN  NaN         NaN

In [60]:
dd.add(data,fill_value=7)

a     b branch     c     d name rollnumbers
0   7.0   8.0    NaN   9.0  10.0  NaN         NaN
1  11.0   NaN    NaN  13.0  14.0  NaN         NaN
2  15.0  16.0    NaN  17.0  18.0  NaN         NaN
3  19.0  20.0    NaN  21.0  22.0  NaN         NaN
4  23.0  24.0    NaN  25.0  26.0  NaN         NaN

In [62]:
np.random.rand(2,4)

array([[0.45462864, 0.40577621, 0.12193771, 0.49297511],
       [0.10147546, 0.93100933, 0.86654019, 0.60465567]])

In [63]:
np.random.randn(1,10)

array([[-0.41044239, -0.66922175, -0.2593764 ,  1.47507853, -0.95882593,
         0.27865758, -1.48940379,  2.76679501, -1.08905014, -0.67261692]])

In [66]:
# Create a data frame with random value
s=pd.DataFrame(np.random.randn(3,4))
s

0         1         2         3
0 -0.988645 -0.275563 -0.094996  1.297002
1 -0.734543  0.815126  0.439417  0.570002
2  0.024867 -0.082833  0.736316 -1.561926

In [69]:
s=pd.DataFrame(np.random.randn(3,4),index=['x','y','z'],columns=['s1','s2','s3','s4'])
s

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110

In [70]:
s.index=['x','y','z']
s

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110

In [71]:
## Reindexing
s1=s.reindex(['x','y','z','w'])
s1

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
w       NaN       NaN       NaN       NaN

In [72]:
s1.isnull().sum()

s1    1
s2    1
s3    1
s4    1
dtype: int64

In [73]:
s1.dropna()

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110

In [76]:
s1.fillna(3)

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
w  3.000000  3.000000  3.000000  3.000000

In [80]:
s1.fillna(method='bfill',axis=1).fillna(1)## backword filling

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
w  1.000000  1.000000  1.000000  1.000000

In [81]:
s1.fillna(method='ffill',axis=1).fillna(1)## farword filling

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
w  1.000000  1.000000  1.000000  1.000000

In [82]:
s1.isnull()

s1     s2     s3     s4
x  False  False  False  False
y  False  False  False  False
z  False  False  False  False
w   True   True   True   True

In [83]:
pd.isna(s1['s4'])

x    False
y    False
z    False
w     True
Name: s4, dtype: bool

In [84]:
## Data replasing
s1

s1        s2        s3        s4
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
w       NaN       NaN       NaN       NaN

In [137]:
## Index sorting and ranking
s2=s1.reindex(['y','z','x','w'])
s2

s4        s2        s1        s3
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110
x  0.591866 -1.012953  0.723037  0.405532
w       NaN       NaN       NaN       NaN

In [138]:
s2.sort_index()

s4        s2        s1        s3
w       NaN       NaN       NaN       NaN
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110

In [139]:
s3=s1.recolumns=(['s4','s2','s1','s3'])
s3

['s4', 's2', 's1', 's3']

In [140]:
s1.sort_index(axis=0)

s4        s2        s1        s3
w       NaN       NaN       NaN       NaN
x  0.591866 -1.012953  0.723037  0.405532
y  0.102470 -0.532243  0.195140 -0.209295
z -2.012395 -1.505415 -0.266656  1.756110

In [141]:
s1.sort_index(axis=1)

s1        s2        s3        s4
x  0.723037 -1.012953  0.405532  0.591866
y  0.195140 -0.532243 -0.209295  0.102470
z -0.266656 -1.505415  1.756110 -2.012395
w       NaN       NaN       NaN       NaN

In [142]:
## Group by
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','ooo','zoo','ooo','oo'],'feature':['q','s','s','p','s']})
animal_df                                                                                                                 

name place feature
0  dog   zoo       q
1  cat   ooo       s
2  cow   zoo       s
3  dog   ooo       p
4  cat    oo       s

In [143]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [144]:
animal_df.groupby('place').count()

name  feature
place               
oo        1        1
ooo       2        2
zoo       2        2

In [145]:
animal_df.groupby(['name','feature']).sum()

place
name feature       
cat  s        ooooo
cow  s          zoo
dog  p          ooo
     q          zoo

In [148]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cat'],'place':['zoo','ooo','zoo','ooo','oo'],'no-legs':[4,2,3,2,np.nan]})
animal_df                  

name place  no-legs
0  dog   zoo      4.0
1  cat   ooo      2.0
2  cow   zoo      3.0
3  dog   ooo      2.0
4  cat    oo      NaN

In [150]:
animal_df["rank1"]=animal_df['no-legs'].rank()
animal_df

name place  no-legs  rank1
0  dog   zoo      4.0    4.0
1  cat   ooo      2.0    1.5
2  cow   zoo      3.0    3.0
3  dog   ooo      2.0    1.5
4  cat    oo      NaN    NaN

In [151]:
animal_df["max-rank"]=animal_df['no-legs'].rank(method="max")
animal_df

name place  no-legs  rank1  max-rank
0  dog   zoo      4.0    4.0       4.0
1  cat   ooo      2.0    1.5       2.0
2  cow   zoo      3.0    3.0       3.0
3  dog   ooo      2.0    1.5       2.0
4  cat    oo      NaN    NaN       NaN

In [152]:
animal_df["first-rank"]=animal_df['no-legs'].rank(method="first")
animal_df

name place  no-legs  rank1  max-rank  first-rank
0  dog   zoo      4.0    4.0       4.0         4.0
1  cat   ooo      2.0    1.5       2.0         1.0
2  cow   zoo      3.0    3.0       3.0         3.0
3  dog   ooo      2.0    1.5       2.0         2.0
4  cat    oo      NaN    NaN       NaN         NaN

In [154]:
animal_df["non-rank"]=animal_df['no-legs'].rank(na_option="bottom")
animal_df

name place  no-legs  rank1  max-rank  first-rank  non-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0
1  cat   ooo      2.0    1.5       2.0         1.0       1.5
2  cow   zoo      3.0    3.0       3.0         3.0       3.0
3  dog   ooo      2.0    1.5       2.0         2.0       1.5
4  cat    oo      NaN    NaN       NaN         NaN       5.0

In [155]:
animal_df["pct-rank"]=animal_df['no-legs'].rank(pct="True")
animal_df

name place  no-legs  rank1  max-rank  first-rank  non-rank  pct-rank
0  dog   zoo      4.0    4.0       4.0         4.0       4.0     1.000
1  cat   ooo      2.0    1.5       2.0         1.0       1.5     0.375
2  cow   zoo      3.0    3.0       3.0         3.0       3.0     0.750
3  dog   ooo      2.0    1.5       2.0         2.0       1.5     0.375
4  cat    oo      NaN    NaN       NaN         NaN       5.0       NaN

In [159]:
## Categorise
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [160]:
data_frame["cc"]=data_frame['y'].astype('category')
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [161]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [163]:
data_frame["cc"].cat.categories=["good","bad","worst","verygood","verybad"]
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9  verygood
4  5  10   verybad

In [164]:
data_frame["cc"]=data_frame["cc"].cat.set_categories(["good","bad","worst","verygood","verybad"])
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9  verygood
4  5  10   verybad

In [165]:
data_frame.sort_values('cc')

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9  verygood
4  5  10   verybad

In [166]:
data_frame.groupby("cc").sum()

x   y
cc             
good      1   6
bad       2   7
worst     3   8
verygood  4   9
verybad   5  10

In [167]:
data_frame.groupby("cc").size()

cc
good        1
bad         1
worst       1
verygood    1
verybad     1
dtype: int64

In [171]:
import pandas as pd
df=pd.read_table("sample.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  


123
0   456
1  8645

In [172]:
df.tail(1)

123
1  8645

In [173]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo